/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// An audio bookmark.
    /// </summary>
    [DataContract(Name = "AudioBookmark")]
    public partial class AudioBookmarkModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AudioBookmarkModel" /> class.
        /// </summary>
        /// <param name="libraryItemId">The ID of the library item the bookmark is for..</param>
        /// <param name="title">The title of the bookmark..</param>
        /// <param name="time">The time (in seconds) the bookmark is at..</param>
        /// <param name="createdAt">The time (in ms since POSIX epoch) when the bookmark was created..</param>
        public AudioBookmarkModel(string libraryItemId = default(string), string title = default(string), decimal time = default(decimal), long createdAt = default(long))
        {
            this.LibraryItemId = libraryItemId;
            this.Title = title;
            this.Time = time;
            this.CreatedAt = createdAt;
        }

        /// <summary>
        /// The ID of the library item the bookmark is for.
        /// </summary>
        /// <value>The ID of the library item the bookmark is for.</value>
        [DataMember(Name = "libraryItemId", EmitDefaultValue = false)]
        public string LibraryItemId { get; set; }

        /// <summary>
        /// The title of the bookmark.
        /// </summary>
        /// <value>The title of the bookmark.</value>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// The time (in seconds) the bookmark is at.
        /// </summary>
        /// <value>The time (in seconds) the bookmark is at.</value>
        [DataMember(Name = "time", EmitDefaultValue = false)]
        public decimal Time { get; set; }

        /// <summary>
        /// The time (in ms since POSIX epoch) when the bookmark was created.
        /// </summary>
        /// <value>The time (in ms since POSIX epoch) when the bookmark was created.</value>
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public long CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AudioBookmarkModel {\n");
            sb.Append("  LibraryItemId: ").Append(LibraryItemId).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
