/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// A collection of books.
    /// </summary>
    [DataContract(Name = "Collection")]
    public partial class CollectionModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CollectionModel" /> class.
        /// </summary>
        /// <param name="id">The ID of the collection..</param>
        /// <param name="libraryId">The ID of the library the collection belongs to..</param>
        /// <param name="userId">The ID of the user that created the collection..</param>
        /// <param name="name">The name of the collection..</param>
        /// <param name="description">The collection&#39;s description. Will be null if there is none..</param>
        /// <param name="books">The books that belong to the collection..</param>
        /// <param name="lastUpdate">The time (in ms since POSIX epoch) when the collection was last updated..</param>
        /// <param name="createdAt">The time (in ms since POSIX epoch) when the collection was created..</param>
        public CollectionModel(string id = default(string), string libraryId = default(string), string userId = default(string), string name = default(string), string description = default(string), List<LibraryItemModel> books = default(List<LibraryItemModel>), long lastUpdate = default(long), long createdAt = default(long))
        {
            this.Id = id;
            this.LibraryId = libraryId;
            this.UserId = userId;
            this.Name = name;
            this.Description = description;
            this.Books = books;
            this.LastUpdate = lastUpdate;
            this.CreatedAt = createdAt;
        }

        /// <summary>
        /// The ID of the collection.
        /// </summary>
        /// <value>The ID of the collection.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// The ID of the library the collection belongs to.
        /// </summary>
        /// <value>The ID of the library the collection belongs to.</value>
        [DataMember(Name = "libraryId", EmitDefaultValue = false)]
        public string LibraryId { get; set; }

        /// <summary>
        /// The ID of the user that created the collection.
        /// </summary>
        /// <value>The ID of the user that created the collection.</value>
        [DataMember(Name = "userId", EmitDefaultValue = false)]
        public string UserId { get; set; }

        /// <summary>
        /// The name of the collection.
        /// </summary>
        /// <value>The name of the collection.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// The collection&#39;s description. Will be null if there is none.
        /// </summary>
        /// <value>The collection&#39;s description. Will be null if there is none.</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// The books that belong to the collection.
        /// </summary>
        /// <value>The books that belong to the collection.</value>
        [DataMember(Name = "books", EmitDefaultValue = false)]
        public List<LibraryItemModel> Books { get; set; }

        /// <summary>
        /// The time (in ms since POSIX epoch) when the collection was last updated.
        /// </summary>
        /// <value>The time (in ms since POSIX epoch) when the collection was last updated.</value>
        [DataMember(Name = "lastUpdate", EmitDefaultValue = false)]
        public long LastUpdate { get; set; }

        /// <summary>
        /// The time (in ms since POSIX epoch) when the collection was created.
        /// </summary>
        /// <value>The time (in ms since POSIX epoch) when the collection was created.</value>
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public long CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CollectionModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LibraryId: ").Append(LibraryId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Books: ").Append(Books).Append("\n");
            sb.Append("  LastUpdate: ").Append(LastUpdate).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
