/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// Stats about a genre in the library.
    /// </summary>
    [DataContract(Name = "GenreStats")]
    public partial class GenreStatsModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GenreStatsModel" /> class.
        /// </summary>
        /// <param name="genre">The name of the genre..</param>
        /// <param name="count">The number of items in the library with this genre..</param>
        public GenreStatsModel(string genre = default(string), int count = default(int))
        {
            this.Genre = genre;
            this.Count = count;
        }

        /// <summary>
        /// The name of the genre.
        /// </summary>
        /// <value>The name of the genre.</value>
        [DataMember(Name = "genre", EmitDefaultValue = false)]
        public string Genre { get; set; }

        /// <summary>
        /// The number of items in the library with this genre.
        /// </summary>
        /// <value>The number of items in the library with this genre.</value>
        [DataMember(Name = "count", EmitDefaultValue = false)]
        public int Count { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GenreStatsModel {\n");
            sb.Append("  Genre: ").Append(Genre).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
