/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// GetEpisodeDownloadsResponseModel
    /// </summary>
    [DataContract(Name = "GetEpisodeDownloadsResponse")]
    public partial class GetEpisodeDownloadsResponseModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEpisodeDownloadsResponseModel" /> class.
        /// </summary>
        /// <param name="currentDownload">currentDownload.</param>
        /// <param name="queue">queue.</param>
        public GetEpisodeDownloadsResponseModel(PodcastEpisodeDownloadModel currentDownload = default(PodcastEpisodeDownloadModel), List<PodcastEpisodeDownloadModel> queue = default(List<PodcastEpisodeDownloadModel>))
        {
            this.CurrentDownload = currentDownload;
            this.Queue = queue;
        }

        /// <summary>
        /// Gets or Sets CurrentDownload
        /// </summary>
        [DataMember(Name = "currentDownload", EmitDefaultValue = false)]
        public PodcastEpisodeDownloadModel CurrentDownload { get; set; }

        /// <summary>
        /// Gets or Sets Queue
        /// </summary>
        [DataMember(Name = "queue", EmitDefaultValue = false)]
        public List<PodcastEpisodeDownloadModel> Queue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetEpisodeDownloadsResponseModel {\n");
            sb.Append("  CurrentDownload: ").Append(CurrentDownload).Append("\n");
            sb.Append("  Queue: ").Append(Queue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
