/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// GetListeningStatsResponseItemsValueModel
    /// </summary>
    [DataContract(Name = "GetListeningStatsResponse_items_value")]
    public partial class GetListeningStatsResponseItemsValueModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetListeningStatsResponseItemsValueModel" /> class.
        /// </summary>
        /// <param name="id">The ID of the library item you listened to..</param>
        /// <param name="timeListening">The time (in seconds) you listened to the library item..</param>
        /// <param name="mediaMetadata">mediaMetadata.</param>
        public GetListeningStatsResponseItemsValueModel(string id = default(string), int timeListening = default(int), BookMetadataModel mediaMetadata = default(BookMetadataModel))
        {
            this.Id = id;
            this.TimeListening = timeListening;
            this.MediaMetadata = mediaMetadata;
        }

        /// <summary>
        /// The ID of the library item you listened to.
        /// </summary>
        /// <value>The ID of the library item you listened to.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// The time (in seconds) you listened to the library item.
        /// </summary>
        /// <value>The time (in seconds) you listened to the library item.</value>
        [DataMember(Name = "timeListening", EmitDefaultValue = false)]
        public int TimeListening { get; set; }

        /// <summary>
        /// Gets or Sets MediaMetadata
        /// </summary>
        [DataMember(Name = "mediaMetadata", EmitDefaultValue = false)]
        public BookMetadataModel MediaMetadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetListeningStatsResponseItemsValueModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TimeListening: ").Append(TimeListening).Append("\n");
            sb.Append("  MediaMetadata: ").Append(MediaMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
