/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// GetLibrarySeriesResponseModel
    /// </summary>
    [DataContract(Name = "GetLibrarySeriesResponse")]
    public partial class GetLibrarySeriesResponseModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetLibrarySeriesResponseModel" /> class.
        /// </summary>
        /// <param name="results">results.</param>
        /// <param name="total">total.</param>
        /// <param name="limit">limit.</param>
        /// <param name="page">page.</param>
        /// <param name="sortBy">sortBy.</param>
        /// <param name="sortDesc">sortDesc.</param>
        /// <param name="filterBy">filterBy.</param>
        /// <param name="minified">minified.</param>
        /// <param name="include">include.</param>
        public GetLibrarySeriesResponseModel(List<SeriesBooksModel> results = default(List<SeriesBooksModel>), int total = default(int), int limit = default(int), int page = default(int), string sortBy = default(string), bool sortDesc = default(bool), string filterBy = default(string), bool minified = default(bool), string include = default(string))
        {
            this.Results = results;
            this.Total = total;
            this.Limit = limit;
            this.Page = page;
            this.SortBy = sortBy;
            this.SortDesc = sortDesc;
            this.FilterBy = filterBy;
            this.Minified = minified;
            this.Include = include;
        }

        /// <summary>
        /// Gets or Sets Results
        /// </summary>
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public List<SeriesBooksModel> Results { get; set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [DataMember(Name = "total", EmitDefaultValue = false)]
        public int Total { get; set; }

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        [DataMember(Name = "limit", EmitDefaultValue = false)]
        public int Limit { get; set; }

        /// <summary>
        /// Gets or Sets Page
        /// </summary>
        [DataMember(Name = "page", EmitDefaultValue = false)]
        public int Page { get; set; }

        /// <summary>
        /// Gets or Sets SortBy
        /// </summary>
        [DataMember(Name = "sortBy", EmitDefaultValue = false)]
        public string SortBy { get; set; }

        /// <summary>
        /// Gets or Sets SortDesc
        /// </summary>
        [DataMember(Name = "sortDesc", EmitDefaultValue = true)]
        public bool SortDesc { get; set; }

        /// <summary>
        /// Gets or Sets FilterBy
        /// </summary>
        [DataMember(Name = "filterBy", EmitDefaultValue = false)]
        public string FilterBy { get; set; }

        /// <summary>
        /// Gets or Sets Minified
        /// </summary>
        [DataMember(Name = "minified", EmitDefaultValue = true)]
        public bool Minified { get; set; }

        /// <summary>
        /// Gets or Sets Include
        /// </summary>
        [DataMember(Name = "include", EmitDefaultValue = false)]
        public string Include { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetLibrarySeriesResponseModel {\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  SortBy: ").Append(SortBy).Append("\n");
            sb.Append("  SortDesc: ").Append(SortDesc).Append("\n");
            sb.Append("  FilterBy: ").Append(FilterBy).Append("\n");
            sb.Append("  Minified: ").Append(Minified).Append("\n");
            sb.Append("  Include: ").Append(Include).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
