/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// GetLibraryResponseModel
    /// </summary>
    [DataContract(Name = "GetLibraryResponse")]
    public partial class GetLibraryResponseModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetLibraryResponseModel" /> class.
        /// </summary>
        /// <param name="filterdata">filterdata.</param>
        /// <param name="issues">issues.</param>
        /// <param name="numUserPlaylists">numUserPlaylists.</param>
        /// <param name="library">library.</param>
        public GetLibraryResponseModel(LibraryFilterDataModel filterdata = default(LibraryFilterDataModel), int issues = default(int), int numUserPlaylists = default(int), LibraryModel library = default(LibraryModel))
        {
            this.Filterdata = filterdata;
            this.Issues = issues;
            this.NumUserPlaylists = numUserPlaylists;
            this.Library = library;
        }

        /// <summary>
        /// Gets or Sets Filterdata
        /// </summary>
        [DataMember(Name = "filterdata", EmitDefaultValue = false)]
        public LibraryFilterDataModel Filterdata { get; set; }

        /// <summary>
        /// Gets or Sets Issues
        /// </summary>
        [DataMember(Name = "issues", EmitDefaultValue = false)]
        public int Issues { get; set; }

        /// <summary>
        /// Gets or Sets NumUserPlaylists
        /// </summary>
        [DataMember(Name = "numUserPlaylists", EmitDefaultValue = false)]
        public int NumUserPlaylists { get; set; }

        /// <summary>
        /// Gets or Sets Library
        /// </summary>
        [DataMember(Name = "library", EmitDefaultValue = false)]
        public LibraryModel Library { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetLibraryResponseModel {\n");
            sb.Append("  Filterdata: ").Append(Filterdata).Append("\n");
            sb.Append("  Issues: ").Append(Issues).Append("\n");
            sb.Append("  NumUserPlaylists: ").Append(NumUserPlaylists).Append("\n");
            sb.Append("  Library: ").Append(Library).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
