/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// GetUserListeningStatsResponseModel
    /// </summary>
    [DataContract(Name = "GetUserListeningStatsResponse")]
    public partial class GetUserListeningStatsResponseModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUserListeningStatsResponseModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetUserListeningStatsResponseModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUserListeningStatsResponseModel" /> class.
        /// </summary>
        /// <param name="totalTime">totalTime (required).</param>
        /// <param name="items">items (required).</param>
        /// <param name="days">days (required).</param>
        /// <param name="dayOfWeek">dayOfWeek (required).</param>
        /// <param name="today">today (required).</param>
        /// <param name="recentSessions">recentSessions (required).</param>
        public GetUserListeningStatsResponseModel(long totalTime = default(long), Dictionary<string, GetUserListeningStatsResponseItemsValueModel> items = default(Dictionary<string, GetUserListeningStatsResponseItemsValueModel>), Dictionary<string, int> days = default(Dictionary<string, int>), Dictionary<string, int> dayOfWeek = default(Dictionary<string, int>), int today = default(int), List<PlaybackSessionModel> recentSessions = default(List<PlaybackSessionModel>))
        {
            this.TotalTime = totalTime;
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new ArgumentNullException("items is a required property for GetUserListeningStatsResponseModel and cannot be null");
            }
            this.Items = items;
            // to ensure "days" is required (not null)
            if (days == null)
            {
                throw new ArgumentNullException("days is a required property for GetUserListeningStatsResponseModel and cannot be null");
            }
            this.Days = days;
            // to ensure "dayOfWeek" is required (not null)
            if (dayOfWeek == null)
            {
                throw new ArgumentNullException("dayOfWeek is a required property for GetUserListeningStatsResponseModel and cannot be null");
            }
            this.DayOfWeek = dayOfWeek;
            this.Today = today;
            // to ensure "recentSessions" is required (not null)
            if (recentSessions == null)
            {
                throw new ArgumentNullException("recentSessions is a required property for GetUserListeningStatsResponseModel and cannot be null");
            }
            this.RecentSessions = recentSessions;
        }

        /// <summary>
        /// Gets or Sets TotalTime
        /// </summary>
        [DataMember(Name = "totalTime", IsRequired = true, EmitDefaultValue = true)]
        public long TotalTime { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, GetUserListeningStatsResponseItemsValueModel> Items { get; set; }

        /// <summary>
        /// Gets or Sets Days
        /// </summary>
        [DataMember(Name = "days", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, int> Days { get; set; }

        /// <summary>
        /// Gets or Sets DayOfWeek
        /// </summary>
        [DataMember(Name = "dayOfWeek", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, int> DayOfWeek { get; set; }

        /// <summary>
        /// Gets or Sets Today
        /// </summary>
        [DataMember(Name = "today", IsRequired = true, EmitDefaultValue = true)]
        public int Today { get; set; }

        /// <summary>
        /// Gets or Sets RecentSessions
        /// </summary>
        [DataMember(Name = "recentSessions", IsRequired = true, EmitDefaultValue = true)]
        public List<PlaybackSessionModel> RecentSessions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetUserListeningStatsResponseModel {\n");
            sb.Append("  TotalTime: ").Append(TotalTime).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  Days: ").Append(Days).Append("\n");
            sb.Append("  DayOfWeek: ").Append(DayOfWeek).Append("\n");
            sb.Append("  Today: ").Append(Today).Append("\n");
            sb.Append("  RecentSessions: ").Append(RecentSessions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
