/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// Book Expanded or Podcast Expanded.
    /// </summary>
    [JsonConverter(typeof(MediaProgressWithMediaMediaModelJsonConverter))]
    [DataContract(Name = "MediaProgressWithMedia_media")]
    public partial class MediaProgressWithMediaMediaModel : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MediaProgressWithMediaMediaModel" /> class
        /// with the <see cref="BookExpandedModel" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of BookExpandedModel.</param>
        public MediaProgressWithMediaMediaModel(BookExpandedModel actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaProgressWithMediaMediaModel" /> class
        /// with the <see cref="PodcastExpandedModel" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of PodcastExpandedModel.</param>
        public MediaProgressWithMediaMediaModel(PodcastExpandedModel actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(BookExpandedModel) || value is BookExpandedModel)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(PodcastExpandedModel) || value is PodcastExpandedModel)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: BookExpandedModel, PodcastExpandedModel");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `BookExpandedModel`. If the actual instance is not `BookExpandedModel`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of BookExpandedModel</returns>
        public BookExpandedModel GetBookExpandedModel()
        {
            return (BookExpandedModel)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `PodcastExpandedModel`. If the actual instance is not `PodcastExpandedModel`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of PodcastExpandedModel</returns>
        public PodcastExpandedModel GetPodcastExpandedModel()
        {
            return (PodcastExpandedModel)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MediaProgressWithMediaMediaModel {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, MediaProgressWithMediaMediaModel.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of MediaProgressWithMediaMediaModel
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of MediaProgressWithMediaMediaModel</returns>
        public static MediaProgressWithMediaMediaModel FromJson(string jsonString)
        {
            MediaProgressWithMediaMediaModel newMediaProgressWithMediaMediaModel = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newMediaProgressWithMediaMediaModel;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(BookExpandedModel).GetProperty("AdditionalProperties") == null)
                {
                    newMediaProgressWithMediaMediaModel = new MediaProgressWithMediaMediaModel(JsonConvert.DeserializeObject<BookExpandedModel>(jsonString, MediaProgressWithMediaMediaModel.SerializerSettings));
                }
                else
                {
                    newMediaProgressWithMediaMediaModel = new MediaProgressWithMediaMediaModel(JsonConvert.DeserializeObject<BookExpandedModel>(jsonString, MediaProgressWithMediaMediaModel.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("BookExpandedModel");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into BookExpandedModel: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(PodcastExpandedModel).GetProperty("AdditionalProperties") == null)
                {
                    newMediaProgressWithMediaMediaModel = new MediaProgressWithMediaMediaModel(JsonConvert.DeserializeObject<PodcastExpandedModel>(jsonString, MediaProgressWithMediaMediaModel.SerializerSettings));
                }
                else
                {
                    newMediaProgressWithMediaMediaModel = new MediaProgressWithMediaMediaModel(JsonConvert.DeserializeObject<PodcastExpandedModel>(jsonString, MediaProgressWithMediaMediaModel.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("PodcastExpandedModel");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into PodcastExpandedModel: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newMediaProgressWithMediaMediaModel;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for MediaProgressWithMediaMediaModel
    /// </summary>
    public class MediaProgressWithMediaMediaModelJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(MediaProgressWithMediaMediaModel).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return MediaProgressWithMediaMediaModel.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return MediaProgressWithMediaMediaModel.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
