/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// ReorderLibrariesRequestInnerModel
    /// </summary>
    [DataContract(Name = "ReorderLibrariesRequest_inner")]
    public partial class ReorderLibrariesRequestInnerModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReorderLibrariesRequestInnerModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReorderLibrariesRequestInnerModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReorderLibrariesRequestInnerModel" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="newOrder">newOrder (required).</param>
        public ReorderLibrariesRequestInnerModel(string id = default(string), int newOrder = default(int))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for ReorderLibrariesRequestInnerModel and cannot be null");
            }
            this.Id = id;
            this.NewOrder = newOrder;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets NewOrder
        /// </summary>
        [DataMember(Name = "newOrder", IsRequired = true, EmitDefaultValue = true)]
        public int NewOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReorderLibrariesRequestInnerModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  NewOrder: ").Append(NewOrder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
