/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// Series with books.
    /// </summary>
    [DataContract(Name = "SeriesBooks")]
    public partial class SeriesBooksModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeriesBooksModel" /> class.
        /// </summary>
        /// <param name="id">The ID of the series..</param>
        /// <param name="name">The name of the series..</param>
        /// <param name="nameIgnorePrefix">The name of the series with any prefix moved to the end..</param>
        /// <param name="nameIgnorePrefixSort">The name of the series with any prefix removed..</param>
        /// <param name="type">Will always be series..</param>
        /// <param name="books">The library items that contain the books in the series..</param>
        /// <param name="addedAt">The time (in ms since POSIX epoch) when the series was added..</param>
        /// <param name="totalDuration">The combined duration (in seconds) of all books in the series..</param>
        public SeriesBooksModel(string id = default(string), string name = default(string), string nameIgnorePrefix = default(string), string nameIgnorePrefixSort = default(string), string type = default(string), List<LibraryItemModel> books = default(List<LibraryItemModel>), long addedAt = default(long), decimal totalDuration = default(decimal))
        {
            this.Id = id;
            this.Name = name;
            this.NameIgnorePrefix = nameIgnorePrefix;
            this.NameIgnorePrefixSort = nameIgnorePrefixSort;
            this.Type = type;
            this.Books = books;
            this.AddedAt = addedAt;
            this.TotalDuration = totalDuration;
        }

        /// <summary>
        /// The ID of the series.
        /// </summary>
        /// <value>The ID of the series.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// The name of the series.
        /// </summary>
        /// <value>The name of the series.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// The name of the series with any prefix moved to the end.
        /// </summary>
        /// <value>The name of the series with any prefix moved to the end.</value>
        [DataMember(Name = "nameIgnorePrefix", EmitDefaultValue = false)]
        public string NameIgnorePrefix { get; set; }

        /// <summary>
        /// The name of the series with any prefix removed.
        /// </summary>
        /// <value>The name of the series with any prefix removed.</value>
        [DataMember(Name = "nameIgnorePrefixSort", EmitDefaultValue = false)]
        public string NameIgnorePrefixSort { get; set; }

        /// <summary>
        /// Will always be series.
        /// </summary>
        /// <value>Will always be series.</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// The library items that contain the books in the series.
        /// </summary>
        /// <value>The library items that contain the books in the series.</value>
        [DataMember(Name = "books", EmitDefaultValue = false)]
        public List<LibraryItemModel> Books { get; set; }

        /// <summary>
        /// The time (in ms since POSIX epoch) when the series was added.
        /// </summary>
        /// <value>The time (in ms since POSIX epoch) when the series was added.</value>
        [DataMember(Name = "addedAt", EmitDefaultValue = false)]
        public long AddedAt { get; set; }

        /// <summary>
        /// The combined duration (in seconds) of all books in the series.
        /// </summary>
        /// <value>The combined duration (in seconds) of all books in the series.</value>
        [DataMember(Name = "totalDuration", EmitDefaultValue = false)]
        public decimal TotalDuration { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeriesBooksModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  NameIgnorePrefix: ").Append(NameIgnorePrefix).Append("\n");
            sb.Append("  NameIgnorePrefixSort: ").Append(NameIgnorePrefixSort).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Books: ").Append(Books).Append("\n");
            sb.Append("  AddedAt: ").Append(AddedAt).Append("\n");
            sb.Append("  TotalDuration: ").Append(TotalDuration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
