/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// An entity displayed in a shelf.
    /// </summary>
    [JsonConverter(typeof(ShelfEntityModelJsonConverter))]
    [DataContract(Name = "ShelfEntity")]
    public partial class ShelfEntityModel : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShelfEntityModel" /> class
        /// with the <see cref="LibraryItemMinifiedModel" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of LibraryItemMinifiedModel.</param>
        public ShelfEntityModel(LibraryItemMinifiedModel actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShelfEntityModel" /> class
        /// with the <see cref="SeriesModel" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SeriesModel.</param>
        public ShelfEntityModel(SeriesModel actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShelfEntityModel" /> class
        /// with the <see cref="AuthorExpandedModel" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of AuthorExpandedModel.</param>
        public ShelfEntityModel(AuthorExpandedModel actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(AuthorExpandedModel))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(LibraryItemMinifiedModel))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(SeriesModel))
                {
                    _actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: AuthorExpandedModel, LibraryItemMinifiedModel, SeriesModel");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `LibraryItemMinifiedModel`. If the actual instance is not `LibraryItemMinifiedModel`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of LibraryItemMinifiedModel</returns>
        public LibraryItemMinifiedModel GetLibraryItemMinifiedModel()
        {
            return (LibraryItemMinifiedModel)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SeriesModel`. If the actual instance is not `SeriesModel`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SeriesModel</returns>
        public SeriesModel GetSeriesModel()
        {
            return (SeriesModel)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `AuthorExpandedModel`. If the actual instance is not `AuthorExpandedModel`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of AuthorExpandedModel</returns>
        public AuthorExpandedModel GetAuthorExpandedModel()
        {
            return (AuthorExpandedModel)ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ShelfEntityModel {\n");
            sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(ActualInstance, ShelfEntityModel.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ShelfEntityModel
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ShelfEntityModel</returns>
        public static ShelfEntityModel FromJson(string jsonString)
        {
            ShelfEntityModel newShelfEntityModel = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newShelfEntityModel;
            }

            try
            {
                newShelfEntityModel = new ShelfEntityModel(JsonConvert.DeserializeObject<AuthorExpandedModel>(jsonString, ShelfEntityModel.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newShelfEntityModel;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into AuthorExpandedModel: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newShelfEntityModel = new ShelfEntityModel(JsonConvert.DeserializeObject<LibraryItemMinifiedModel>(jsonString, ShelfEntityModel.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newShelfEntityModel;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into LibraryItemMinifiedModel: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newShelfEntityModel = new ShelfEntityModel(JsonConvert.DeserializeObject<SeriesModel>(jsonString, ShelfEntityModel.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newShelfEntityModel;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SeriesModel: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for ShelfEntityModel
    /// </summary>
    public class ShelfEntityModelJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ShelfEntityModel).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return ShelfEntityModel.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return ShelfEntityModel.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
