/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// UpdateItemChaptersRequestModel
    /// </summary>
    [DataContract(Name = "UpdateItemChaptersRequest")]
    public partial class UpdateItemChaptersRequestModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateItemChaptersRequestModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateItemChaptersRequestModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateItemChaptersRequestModel" /> class.
        /// </summary>
        /// <param name="chapters">chapters (required).</param>
        public UpdateItemChaptersRequestModel(List<UpdateItemChaptersRequestChaptersInnerModel> chapters = default(List<UpdateItemChaptersRequestChaptersInnerModel>))
        {
            // to ensure "chapters" is required (not null)
            if (chapters == null)
            {
                throw new ArgumentNullException("chapters is a required property for UpdateItemChaptersRequestModel and cannot be null");
            }
            this.Chapters = chapters;
        }

        /// <summary>
        /// Gets or Sets Chapters
        /// </summary>
        [DataMember(Name = "chapters", IsRequired = true, EmitDefaultValue = true)]
        public List<UpdateItemChaptersRequestChaptersInnerModel> Chapters { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateItemChaptersRequestModel {\n");
            sb.Append("  Chapters: ").Append(Chapters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
