/*
 * Audiobookshelf API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Audiobookshelf.ClientLibrary.Client.OpenAPIDateConverter;

namespace Audiobookshelf.ClientLibrary.Model
{
    /// <summary>
    /// UpdatePlaylistRequestModel
    /// </summary>
    [DataContract(Name = "UpdatePlaylistRequest")]
    public partial class UpdatePlaylistRequestModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePlaylistRequestModel" /> class.
        /// </summary>
        /// <param name="name">The playlist&#39;s name..</param>
        /// <param name="description">The playlist&#39;s description..</param>
        /// <param name="coverPath">The path of the playlist&#39;s cover..</param>
        /// <param name="items">The items in the playlist..</param>
        public UpdatePlaylistRequestModel(string name = default(string), string description = default(string), string coverPath = default(string), List<PlaylistItemModel> items = default(List<PlaylistItemModel>))
        {
            this.Name = name;
            this.Description = description;
            this.CoverPath = coverPath;
            this.Items = items;
        }

        /// <summary>
        /// The playlist&#39;s name.
        /// </summary>
        /// <value>The playlist&#39;s name.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// The playlist&#39;s description.
        /// </summary>
        /// <value>The playlist&#39;s description.</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// The path of the playlist&#39;s cover.
        /// </summary>
        /// <value>The path of the playlist&#39;s cover.</value>
        [DataMember(Name = "coverPath", EmitDefaultValue = true)]
        public string CoverPath { get; set; }

        /// <summary>
        /// The items in the playlist.
        /// </summary>
        /// <value>The items in the playlist.</value>
        [DataMember(Name = "items", EmitDefaultValue = false)]
        public List<PlaylistItemModel> Items { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdatePlaylistRequestModel {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  CoverPath: ").Append(CoverPath).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
